export const REQUEST_DATA = 'REQUEST_DATA';
export const UPLOAD_ARTWORK = 'UPLOAD_ARTWORK';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SAVE_DATA = 'SAVE_DATA';
export const FETCH_EXPERIMENT_DATA = 'FETCH_EXPERIMENT_DATA';
export const FETCH_USER_RATINGS = 'FETCH_USER_RATINGS';
